export const CONTEXT_MENU_ITEMS = [
  { icon: 'content_copy', label: 'Copy commit ID',    shortcut: '⌘C', copySha: true },
  { icon: 'sell',         label: 'Copy commit infos', shortcut: null,  copyInfo: true },
  { divider: true },
  { icon: 'difference',   label: 'Compare with local', shortcut: '⌘D', compareWithLocal: true },
  { divider: true },
  { icon: 'download_for_offline', label: 'Checkout commit',            shortcut: null, disabled: true },
  { icon: 'call_split',           label: 'Create branch from here',    shortcut: null, disabled: true },
  { icon: 'sell',                 label: 'Create tag at commit',        shortcut: null, disabled: true },
  { divider: true },
  { icon: 'undo',         label: 'Revert commit',                      shortcut: null, disabled: true },
  { icon: 'restart_alt',  label: 'Reset current branch to here',       shortcut: null, disabled: true },
  { divider: true },
  { icon: 'open_in_new',  label: 'Open in remote',                     shortcut: null, disabled: true },
];
